### ISSUE TITLE
Version Update

### ISSUE THREAD

**Issue by sebastianzillessen** [jejacks0n/teaspoon#494]
Hi,

the latest version published was 1.1.5. 

Since then some useful features have been submitted to the project. Are you planning on releasing a new version soon?

Cheers,

Sebastian

**Comment by marienfressinaud** [comment]
Hi,

The latest version of Teaspoon is 2 years old, and we are facing the very annoying https://github.com/jejacks0n/teaspoon/issues/443#issuecomment-332712695 issue on several of our projects, fixed by https://github.com/jejacks0n/teaspoon/pull/529 which is in `master` but still not released in any official version.

Do you plan a new release soon? How can we help you to make it happen?

Thanks!

**Comment by trcarden** [comment]
Others are also interested in getting a new gem version cut:
 - https://github.com/jejacks0n/teaspoon/issues/558
 - https://github.com/jejacks0n/teaspoon/pull/519#issuecomment-480599565

**Comment by jbosse** [comment]
The published gem is really old yet the repo seems very active lately. Some sort of update to the top of the README as to what the release plan is would be really helpful.

We have two major issues (headlessness and removing coffee script) forcing us to remove teaspoon but it looks like they have already been resolved in master.

**Comment by jejacks0n** [comment]
I'm trying to get things merged in and released. Would welcome any help getting existing PRs shored up and passing on CI.

**Comment by jejacks0n** [comment]
@pablobm -- I have CI passing, so that might make things easier?

**Comment by pablobm** [comment]
@jejacks0n - Sorry, what do you mean? Reviewing existing PRs? Cutting new gem versions?
