### ISSUE TITLE
Allow to configure driver path

### ISSUE THREAD

**Issue by Erowlin** [jejacks0n/teaspoon#542]
I'm looking at a way to tell Teaspoon where the driver is installed. For now, it looks only in ~/.driver, which is not suitable for caching in circleCI. 

For instance with PhantomJS, I would like to do `DRIVER_PATH=my_cached_folder/phantomjs bundle exec teaspoon`

Thanks.

**Comment by jejacks0n** [comment]
It just looks in your PATH for it. If you want to, you can just do something like (speculating, haven't tried it):

```
PATH="my_cached_folder:$PATH" bundle exec teaspoon
```

**Comment by Erowlin** [comment]
It doesn't work, I just tried it. 

I don't want to be agressive, wondering why you close the issue without letting me the time to: 

1. Explain furthermore if needed
2. Try your solution to see if it works
3. Actually closing while speculating

Thanks!

**Comment by jejacks0n** [comment]
Because if it’s in your path it should work. Literally for everybody else that’s ever used it that’s true. If you can get a response from `which phantomjs` it works in teaspoon. This isn’t a support channel, I’m simply explaining how it works, I didn’t mean to offend by closing your issue.

---
Jeremy Jackson
