### ISSUE TITLE
Verify that tests are run (when syntax error)

### ISSUE THREAD

**Issue by joshm1204** [jejacks0n/teaspoon#563]
I noticed that if I make a syntax error in my teaspoon tests, a whole section of tests won't run.  Unless I am manually counting all the test, I don't know the total number that should be run.  So my fear is that I could make a mistake and a whole section of my tests never execute.

Is there a way to prevent this?  How can a get teaspoon-jasmine to error if it can not run a series of tests?

**Comment by jejacks0n** [comment]
This goes way back if I recall -- it's kind of an interesting thing because the error happens before teaspoon can do anything about it. If you think about it, a syntax error would be handled at parse time, which teaspoon can't hook into at any level, because it too is being parsed and not executed at this point.

**Comment by jejacks0n** [comment]
if you're doing any sort of transpiling, this can be captured by the system doing that though.
