### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by dylnclrk** [jejacks0n/teaspoon#575]
Hi, just wanted to voice my support of a new Teaspoon release. There are some features on master that I'd love to use. Thanks!

**Comment by danmayer** [comment]
This would be really helpful, installing from github with our current workflow ends up breaking our gem cache for every CI run ;(

**Comment by jejacks0n** [comment]
Done! Let me know how it works out. I don't think I need to update/push any of the specific ones like jasmine or mocha, so let me know if this fits your needs.

**Comment by danmayer** [comment]
our issue is actually with `teaspoon-jasmine`

`gem 'teaspoon-jasmine', github: "jejacks0n/teaspoon"`

Although, I think I justed figured out how to fix our CI cache issue by moving to bundler 2. The issue we had is bundler check would always fail due to:

```
The git source `git://github.com/jejacks0n/teaspoon.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
```

and bundler 2.x moves to a secure by default github install flow.
